### DISCUSSION TITLE
how to set user pass in pipe

### DISCUSSION THREAD

**Discussion by dmitriy-udoratin** [tg123/sshpiper#201] [Q&A] [answered]
hey, 

in yaml driver it's possible to set user pass as
```
- username: user
    ignore_hostkey: true
    upstream_host: host
    authmap:
      mapped_username: mapped_user
      from:
      - type: password
        password: 123456
      to:
        type: privatekey
        private_key: /var/sshpiper/hosts/host/id_rsa
```

to connect with pass and map user as mapped_user
user@gateway -> pass -> mapped_user@host

how is it supposed to do and set pass in kubernetes plugin?
```
metadata:
  name: user_pipe
spec:
  from:
  - username: user
  to:
    host: host
    username: mapped_user
    private_key_secret:
      name: host
    ignore_hostkey: true
```
