### ISSUE TITLE
Use password instead of key?

### ISSUE THREAD

**Issue by nik736** [tg123/sshpiper#144]
Hi there, is it possible to use password auth instead of using ssh keys? My use-case would be to use the yaml plugin and ideally provide username + password there that will be used for authentication.

Thanks :)

**Comment by tg123** [comment]
```
  to:
    host: host-publickey:2222
    username: "user"
    password: "11111
```
