### ISSUE TITLE
A publickey pipe will cause re-mapping to fail in kubernetes

### ISSUE THREAD

**Issue by MoGuGuai-hzr** [tg123/sshpiper#394]
I created `sshpiper` and two test pods using the following files in k8s:

1. `sshpiper-service.yaml`: Used to launch `sshpiper`.
2. `password-test.yaml`: Only for password login.
3. `publickey-test.yaml`: For login using either a public key or a password.

If I only start items 1 and 2, I can normally log in using `ssh password_test@127.0.0.1 -p 30022`.

However, if I enable item 3, then I must use `ssh password_test@127.0.0.1 -p 30022 -o PubkeyAuthentication=no` to log in.

I saw a similar issue in #12 , and it seems to have been resolved. Did I configure something incorrectly?

```yaml
# sshpiper-service.yaml
---
# sshpiper Service
apiVersion: v1
kind: Service
metadata:
  name: sshpiper
spec:
  selector:
    app: sshpiper
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 30022
  type: NodePort
---
apiVersion: v1
data:
  server_key: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCWUhWV01lNzVDZ3Rzdm5rOWlTekJFU3hSdjdMb3U3K0tVbndmb3VnNzcxZ0FBQUpEQnArS0d3YWZpCmhnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQllIVldNZTc1Q2d0c3ZuazlpU3pCRVN4UnY3TG91NytLVW53Zm91Zzc3MWcKQUFBRUJKSDU3eTFaRTUxbVo2a2VsWUR0eDQ1ajBhZGdsUk5CY0pZOE94YTY4TEJWZ2RWWXg3dmtLQzJ5K2VUMkpMTUVSTApGRy9zdWk3djRwU2ZCK2k2RHZ2V0FBQUFEV0p2YkdsaGJrQjFZblZ1ZEhVPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: sshpiper-server-key
type: Opaque
---
# sshpiper Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshpiper-deployment
  labels:
    app: sshpiper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshpiper
  template:
    metadata:
      labels:
        app: sshpiper
    spec:
      serviceAccountName: sshpiper-account
      containers:
        - name: sshpiper
          image: farmer1992/sshpiperd:full-v1.3.0
          ports:
            - containerPort: 2222
          env:
            - name: PLUGIN
              value: "kubernetes"
            - name: SSHPIPERD_SERVER_KEY
              value: "/serverkey/ssh_host_ed25519_key"
            - name: SSHPIPERD_LOG_LEVEL
              value: "trace"
          volumeMounts:
            - name: sshpiper-server-key
              mountPath: "/serverkey/"
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: sshpiper-server-key
          secret:
            secretName: sshpiper-server-key
            items:
              - key: server_key
                path: ssh_host_ed25519_key
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sshpiper-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["sshpiper.com"]
    resources: ["pipes"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-sshpiper
subjects:
  - kind: ServiceAccount
    name: sshpiper-account
roleRef:
  kind: Role
  name: sshpiper-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshpiper-account
```

```yaml
# password-test.yaml
---
# Pipe
apiVersion: sshpiper.com/v1beta1
kind: Pipe
metadata:
  name: pipe-password
spec:
  from:
    - username: "password_test"
  to:
    host: pipe-password:2222
    username: "user"
    ignore_hostkey: true
---
apiVersion: v1
kind: Service
metadata:
  name: pipe-password
spec:
  selector:
    app: pipe-password
  ports:
    - protocol: TCP
      port: 2222
---
# sshd Pod
apiVersion: v1
kind: Pod
metadata:
  name: pipe-password
  labels:
    app: pipe-password
spec:
  containers:
    - name: pipe-password
      imagePullPolicy: IfNotPresent
      image: lscr.io/linuxserver/openssh-server:latest
      ports:
        - containerPort: 2222
      env:
        - name: PASSWORD_ACCESS
          value: "true"
        - name: USER_PASSWORD
          value: "pass"
        - name: USER_NAME
          value: "user"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
```

```yaml
# publickey-test.yaml
---
apiVersion: v1
data:
  ssh-privatekey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCOHhKd1BtZXBvZFpoV2lMM2t0anN2UGM0ZGgwUk4wWTZTT3d0eUI3bkFwUUFBQUpqVEhRN3EweDBPCjZnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQjh4SndQbWVwb2RaaFdpTDNrdGpzdlBjNGRoMFJOMFk2U093dHlCN25BcFEKQUFBRUQzRE9yaWZSazQ1NVMxZkdyaHZ5bk15QmQwaHJmMXo5OWM2aG0yS2pVaC8zekVuQStaNm1oMW1GYUl2ZVMyT3k4OQp6aDJIUkUzUmpwSTdDM0lIdWNDbEFBQUFFWFJsYzNSQWMzTm9jR2x3WlhJdVkyOXRBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: pipe-publickey-key
type: kubernetes.io/ssh-auth
---
# Pipe
apiVersion: sshpiper.com/v1beta1
kind: Pipe
metadata:
  name: pipe-publickey
  annotations:
    privatekey_field_name: ssh-privatekey # this is optional, default is ssh-privatekey
spec:
  from:
    - username: "publickey_test"
      authorized_keys_data: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHzEnA+Z6mh1mFaIveS2Oy89zh2HRE3RjpI7C3IHucCl test@sshpiper.com"
  to:
    host: pipe-publickey:2222
    username: "user"
    private_key_secret:
      name: pipe-publickey-key
    ignore_hostkey: true
---
apiVersion: v1
kind: Service
metadata:
  name: pipe-publickey
spec:
  selector:
    app: pipe-publickey
  ports:
    - protocol: TCP
      port: 2222
---
apiVersion: v1
kind: Pod
metadata:
  name: pipe-publickey
  labels:
    app: pipe-publickey
spec:
  containers:
    - name: pipe-publickey
      image: lscr.io/linuxserver/openssh-server:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 2222
      env:
        - name: USER_NAME
          value: "user"
        - name: PASSWORD_ACCESS
          value: "true"
        - name: USER_PASSWORD
          value: "pass"
        - name: PUBLIC_KEY
          value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHzEnA+Z6mh1mFaIveS2Oy89zh2HRE3RjpI7C3IHucCl test@sshpiper.com"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
```
