### ISSUE TITLE
YAML Plugin add regex match group

### ISSUE THREAD

**Issue by OwOchle** [tg123/sshpiper#424]
Add a way to access match group of regex of *from username* inside *to username* to permit things like
```
- from:
    - username: "srv_(.*)"
      username_regex_match: true
  to:
    host: host-password:2222
    username: "$1"
    ignore_hostkey: true
```
then `srv_root` would redirect to user `root` on host-password, `srv_user1` to user `user1` etc...
