### ISSUE TITLE
Further information on username_regex_match upstream

### ISSUE THREAD

**Issue by robertgates55** [tg123/sshpiper#54]
Hey - I think this project could be exactly what I'm after, but I'm struggling to configure it the way I need to.

```
steve@ ------>|            |     /---> upstream1.svc:22
              |  sshpiper  | ---+
dave@  ------>|            |     \---> upstream2.svc:22
```

Ideally, I'd like the upstreams themselves to be doing the hostkey verification - I'd like sshpiper to do as little as possible except route based on username.

What config is needed for this? I assume I need to create pipes using `/sshpiperd pipe add -n steve -u upstream1.svc` (& dave)?

If so, then how does the `sshpiperd.yaml` & `SSHPIPERD_UPSTREAM_YAML_FILE` affect the routing? I have:
sshpiperd.yaml

```
version: 1
pipes:
- username: ^dave.*$
  username_regex_match: true
  upstream_host: host2
  ignore_hostkey: true
- username: ^steve.*$
  username_regex_match: true
  upstream_host: host1
  ignore_hostkey: true
```
but I can't see that this is being used yet. Should passing the YAML file mean I don't have to run the `sshpiperd pipe add` commands?
