### ISSUE TITLE
docs: YAML plugin - `from.trusted_user_ca_keys` feature support

### ISSUE THREAD

**Issue by polarathene** [tg123/sshpiper#559]
Similar to improving the `yaml` plugin docs for [`to.password` + `to.ignore_hostkey`](https://github.com/tg123/sshpiper/issues/555), support for downstream auth via SSH certificates was added but presently that feature support is not as easily discoverable due to lack of documentation.

This only requires setting `from.trusted_user_ca_keys` like you would with OpenSSH `sshd` config setting `TrustedUserCAKeys`. Followed by provisioning a SSH user certificate with a principal that includes `from.username`.

Example:

```yaml
version: "1.0"
pipes:
  - from:
      - username: hello
        trusted_user_ca_keys: /etc/sshpiperd/server/ca-key-user_ed25519.pub
    to:
      host: some-service.example.internal:22
      username: world
      private_key: /etc/sshpiperd/client/id_ed25519
      known_hosts: /etc/sshpiperd/client/known_hosts
```

The support by sshpiper is only for downstream clients connecting to sshpiper. There is no equivalent support to use a SSH User Certificate when sshpiper is connecting to an upstream SSH host.

## Reference

https://github.com/tg123/sshpiper/blob/5a2aeeea1f76c2038c22fa5e8503b7505a72741e/plugin/yaml/schema.json#L79-L104

Oct 2024, SSH certificates auth support was requested and implemented for [`k8s` + `yaml` plugins](https://github.com/tg123/sshpiper/issues/452#issuecomment-2466690216):
- https://github.com/tg123/sshpiper/pull/467
- https://github.com/tg123/sshpiper/issues/452

[Related](https://github.com/tg123/sshpiper/issues/452#issuecomment-2426178921) external plugin?: https://github.com/tg123/sshpiper-openpubkey

**Comment by polarathene** [comment]
## Reproduction:

For the benefit of others, here's a full reproduction `compose.yaml` to play with or reference.

```console
# Blank slate start with SSH keys provisioned:
$ docker compose down --volumes && docker compose run --rm -it ssh-setup && docker compose up -d --force-recreate
Signed user key /srv/ssh-client/id_ed25519-cert.pub: id "root@ssh-client" serial 0 for root,hello valid from 2025-04-11T03:02:00 to 2025-04-12T03:03:50

# Default `ssh hello@ssh-proxy`, provide the password `secret` to login
# NOTE: No trusted CA config for this user, password only.
$ docker compose run --rm -it ssh-client

# Change to `root` user, pubkey auth is used with SSH User Certificate for trust:
$ docker compose run --rm -it ssh-client ssh root@ssh-proxy

# Equivalent but direct connection from `ssh-client` to `ssh-server`:
$ docker compose run --rm -it ssh-client ssh world@some-service.example.internal
$ docker compose run --rm -it ssh-client ssh root@some-service.example.internal
```

```yaml
name: example

# Common base fragment for a custom image that is shared across containers: `ssh-client`, `ssh-server`, `ssh-setup`
x-ssh-base: &ssh-base
    image: localhost/openssh
    init: true
    build:
      dockerfile_inline: |
        FROM alpine
        RUN <<HEREDOC
          apk add openssh-client openssh-server

          # Add custom user + group `world`, then set the password as `secret`:
          addgroup --gid 500 world
          adduser --ingroup world --uid 500 --disabled-password world
          echo 'world:secret' | chpasswd
        HEREDOC

services:
  ssh-proxy:
    image: farmer1992/sshpiperd:full-v1.4.7 # `:full` is required for the `yaml` plugin
    environment:
      PLUGIN: yaml
      SSHPIPERD_YAML_CONFIG: /etc/sshpiperd/config.yaml
    # Config and volumes content would need to match the default `1000` UID ownership
    # Alternatively run sshpiperd as root (UID 0):
    user: 0:0
    volumes:
      - ssh-client:/etc/sshpiperd/client/:ro
      - ssh-server:/etc/sshpiperd/server/:ro
    configs:
      # YAML plugin config:
      - source: ssh-proxy-config
        target: /etc/sshpiperd/config.yaml
        mode: 0400
        #uid: '1000' # Uncomment if not setting `user: 0:0`
    # Delay start until volumes are provisioned via `ssh-setup`:
    depends_on:
      ssh-setup:
        condition: service_completed_successfully

  ssh-server:
    <<: *ssh-base
    command: /usr/sbin/sshd -D
    hostname: some-service.example.internal
    configs:
      - source: sshd-config
        target: /etc/ssh/sshd_config
    volumes:
      # SSH CA + SSH host key pairs:
      - ssh-server:/etc/ssh/keys/:ro
      # Trust the SSH client public key (used by containers: ssh-client / ssh-proxy):
      # NOTE: For `world` user pubkey auth support, change this target to `/home/world/.ssh/authorized_keys`.
      - type: volume
        source: ssh-client
        target: /root/.ssh/authorized_keys
        read_only: true
        volume:
          nocopy: true
          subpath: id_ed25519.pub
    # Despite this dependency requirement, the `ssh-client` volume above will fail early
    # if `ssh-setup` is not manually run first as the `subpath` is verified prior.
    depends_on:
      ssh-setup:
        condition: service_completed_successfully

  ssh-client:
    <<: *ssh-base
    scale: 0 # Prevents starting this container during `docker compose up`
    command: ssh hello@ssh-proxy
    # Custom config to simplify `ssh` command options
    configs:
      - source: ssh-hosts
        target: /root/.ssh/config
    volumes:
      # Normally these files would be in `/root/.ssh`, but this avoids persisting `known_hosts` to the volume.
      # Non-issue if `ssh-proxy` were to instead persist the SSH host key (generated by sshpiper).
      - ssh-client:/root/.ssh/keys/

  # Runs a custom script to provision the keys,
  # Normally these are already provisioned at the downstream + upstream hosts.
  ssh-setup:
    <<: *ssh-base
    command: provision-keys.sh
    volumes:
      - ssh-client:/srv/ssh-client/
      - ssh-server:/srv/ssh-server/
    configs:
      - source: setup-ssh-keys
        target: /usr/local/bin/provision-keys.sh
        mode: 500

configs:
  ssh-proxy-config:
    content: |
      version: "1.0"
      pipes:
        # from (SSH server config) => SSH Client (downstream) to sshpiperd
        # to   (SSH client config) => sshpiperd to SSH Server (upstream)

        # SSH User Certificate example: root => root
        - from:
            # Choose a username to map from the client connection to the target host
            # `authorized_keys` to trust by client public key
            # `trusted_user_ca_keys` to trust by client SSH user certificate
            - username: root
              trusted_user_ca_keys: /etc/sshpiperd/server/ca-key-user_ed25519.pub
              #authorized_keys: /etc/sshpiperd/client/id_ed25519.pub
            # This example will fail as the username was not added as a principal to the certificate:
            - username: world
              trusted_user_ca_keys: /etc/sshpiperd/server/ca-key-user_ed25519.pub
          to:
            host: some-service.example.internal:22
            username: root
            private_key: /etc/sshpiperd/client/id_ed25519
            known_hosts: /etc/sshpiperd/client/known_hosts

        # NOTE: While `hello` is a valid principal, configuring `from.trusted_user_ca_keys` here
        # would prevent the password prompt from working with "Permission denied, please try again"
        # this is the same problem for `from.authorized_keys`.
        - from:
            # If no `from` trust attribute was configured, the client receives a password prompt to pass to target host.
            # NOTE: Password auth to the target host should not set `private_key`.
            - username: hello
          to:
            host: some-service.example.internal:22
            username: world
            known_hosts: /etc/sshpiperd/client/known_hosts

  sshd-config:
    content: |
      # NOTE: If more than one host key is configured for sshd,
      # sshpiper does not support negotiating compatible key exchanges
      # it will only select the first one offered by ssh-server.
      HostKey /etc/ssh/keys/ssh_host_ed25519_key

      # Optional: ssh-client => ssh-server
      # NOTE: sshpiper does not support SSH User Certificate auth to a target host (upstream).
      TrustedUserCAKeys /etc/ssh/keys/ca-key-user_ed25519.pub

      # Optional - Skip printing content of /etc/motd upon login:
      PrintMotd no

  ssh-hosts:
    content: |
      # Common settings for these two hosts:
      Host *.example.internal ssh-proxy
        IdentityFile = /root/.ssh/keys/id_ed25519
        # Automatically trust new hosts when missing entry in known_hosts (skips prompt for TOFU):
        StrictHostKeyChecking = accept-new

      # This service defaults to listening on port 2222 instead:
      Host ssh-proxy
        Port = 2222

  # NOTE: `$` will be interpolated from ENV by Docker Compose (opt-out via escaping by replacing `$` => `$$`)
  setup-ssh-keys:
    content: |
      #!/bin/ash

      if [[ -f /srv/ssh-client/id_ed25519 ]]; then
        echo 'SSH keys already provisioned'
        exit
      fi

      SSH_CLIENT='/srv/ssh-client'
      SSH_SERVER='/srv/ssh-server'

      # Key-based auth setup:
      # Create SSH Client and SSH Server (Host) keys
      # NOTE: sshpiper passphrase compatibility is flakey (prompting for it multiple times). Use `-N ''` for empty passphrase
      ssh-keygen -q -t ed25519 -N '' -f "$${SSH_CLIENT}/id_ed25519" -C 'Client Key (root@ssh-client)'
      ssh-keygen -q -t ed25519 -N '' -f "$${SSH_SERVER}/ssh_host_ed25519_key" -C 'Host Key (some-service.example.internal)'

      # Have sshpiper use this file to trust `ssh-server` (alternatively use `ignore_hostkey: true`):
      echo "some-service.example.internal $(cat $${SSH_SERVER}/ssh_host_ed25519_key.pub)" > "$${SSH_CLIENT}/known_hosts"

      # SSH User Certificate - Create the CA key, then sign the client public key:
      ssh-keygen -q -t ed25519 -N '' -f "$${SSH_SERVER}/ca-key-user_ed25519" -C 'Certficate Authority (User) for *.example.internal'
      ssh-keygen -s "$${SSH_SERVER}/ca-key-user_ed25519" -V '+1d' -I 'root@ssh-client' -n root,hello "$${SSH_CLIENT}/id_ed25519.pub"

volumes:
  ssh-client: {}
  ssh-server: {}
```

**NOTE:** Avoid using SSH key passphrase for the client key as this seems to have bad UX with sshpiper (_notably when downstream+upstream configs are password oriented but the client configures `ssh -i` prompting for passphrase many times redundantly_)
  - ❌ `ssh -i /tmp/ssh-client/example -o StrictHostKeyChecking=accept-new hello@ssh-proxy` (_passphrase prompt that never works until switching to password prompt for the `hello@ssh-proxy` user, which handles the password for `world@ssh-server`_)
  - ✅ `ssh -i /tmp/ssh-client/example -o StrictHostKeyChecking=accept-new world@some-service.example.internal` (_straight to password prompt for `world@ssh-server` user_)
