### ISSUE TITLE
SFTP Proxy Questions

### ISSUE THREAD

**Issue by robertgates55** [tg123/sshpiper#56]
I have an upstream service running an SFTP server, which I can authenticate to using my private key (ie it has been provided the public key)

I'd like to be able to put sshpiper between me and this service; and have my private_key authenticate with the upstream SFTP server - but I'm getting upstream sftp authentication errors when going via sshpiper.

My yaml config is:
```
version: 1
pipes:
- username: robertgates
  username_regex_match: false
  upstream_host: sftp:8022
  ignore_hostkey: true
```

Is this expected?

Is this (passthrough) possible:
```
client | sshpiper | upstream
 PK_1  >   ...    >   PK_1
```

Or do I have to map the auth to a second keypair?:
```
client |   sshpiper  | upstream
 PK_1  > PK_1 | PK_2 >   PK_2
```
