### ISSUE TITLE
Consider dropping `ENTRYPOINT`

### ISSUE THREAD

**Issue by polarathene** [tg123/sshpiper#562]
You could opt for the entrypoint ENV to default via the `Dockerfile` instead?:

```Dockerfile
ENV SSHPIPERD_SERVER_KEY_GENERATE_MODE=notexist
```

Similar could be done for `PLUGIN`, however you'd not be able to use the variable reference as part of the default `CMD` which kind of defeats the purpose there. Instead you'd just have something like this:

```Dockerfile
# ENTRYPOINT calls the command directly, while CMD provides flexibility to command args:
ENTRYPOINT ["/sshpiperd/sshpiperd"]
CMD ["/sshpiperd/plugins/workingdir"]
```

The existing entrypoint allows overriding `PLUGIN` via a container override to the command, such as:

```bash
docker run farmer1992/sshpiperd:full /sshpiperd/plugins/yaml
```

Or with `compose.yaml`:

```yaml
services:
  ssh-proxy:
    image: farmer1992/sshpiperd:full
    command: /sshpiperd/plugins/yaml
```

That style is required for more than one plugin AFAIK, which makes `PLUGIN` as an ENV not that useful?

You could probably take these args as absolute paths or relative paths? In which case for relative, instead of:

```
docker run farmer1992/sshpiperd:full /sshpiperd/plugins/yaml /sshpiperd/plugins/workingdir
```

it could be?:

```
docker run farmer1992/sshpiperd:full yaml workingdir
```

I haven't used your project that extensively, so presumably the relative path would need to support configuring the plugins directory? Then for the image that could be configured in the `Dockerfile` as ENV and the user doesn't have to think about it?

---

This would make https://github.com/tg123/sshpiper/pull/561 redundant as no separate `entrypoint.sh` would be necessary. Alternatively users can do as [I have before](https://github.com/tg123/sshpiper/issues/559#issuecomment-2798373009):

```yaml
services:
  ssh-proxy:
    image: farmer1992/sshpiperd:full # `:full` is required for the `yaml` plugin
    # Prefer running the container user as root, without redundant entrypoint:
    user: 0:0
    entrypoint: ["/sshpiperd/sshpiperd"]
    command: -port 22 /sshpiperd/plugins/yaml
    environment:
      # Not required due to manual `entrypoint` + `command` above:
      #PLUGIN: yaml
      SSHPIPERD_YAML_CONFIG: /etc/sshpiperd/config.yaml
      # Optionally enable to generate an SSH host keypair (ed25519):
      # Connecting clients will trust this host key via updating their known_hosts file
      SSHPIPERD_SERVER_KEY_GENERATE_MODE: notexist
```

would become:

```yaml
services:
  ssh-proxy:
    image: farmer1992/sshpiperd:full # `:full` is required for the `yaml` plugin
    user: 0:0
    command: -port 22 /sshpiperd/plugins/yaml
    environment:
      SSHPIPERD_YAML_CONFIG: /etc/sshpiperd/config.yaml
    configs:
      # YAML plugin config:
      - source: ssh-proxy-config
        target: /etc/sshpiperd/config.yaml
        mode: 0400
        #uid: '1000' # Uncomment if not setting `user: 0:0`
```

**NOTE:** `user: 0:0` to reset back to root user is for convenience (_both with `configs` or data volumes_).
- That'd be a separate concern, but personally I don't see a need to run the container as a non-root user, it often causes more problems / friction than necessary 😅 (_those that want to run as a non-root user should be setting it to a non-root UID/GID that suits them, `1000:1000` may not be much better security wise should that escape to the host and that user on a dev machine has sudoless access to the Docker daemon, you're practically root already then_)
- Instead it's better to run a container as rootless instead of rootful (_this is different from container root vs container non-root user_).

## Reference

https://github.com/tg123/sshpiper/blob/95642617d36d6a5a4b51fee36d35ee4f898369ec/Dockerfile#L38

https://github.com/tg123/sshpiper/blob/95642617d36d6a5a4b51fee36d35ee4f898369ec/entrypoint.sh#L1-L7
