### ISSUE TITLE
[k8s] How to point to a sftp server in a different namespace?

### ISSUE THREAD

**Issue by rjbaat** [tg123/sshpiper#68]
Hi all,
I have a SFTP container running on my k8s cluster. Now I want to map sshpiper to it with the pipe manifest. 
I already tried this to use the dns to map the ssh pipe to a different service in a different namespace:

```
apiVersion: pockost.com/v1beta1
kind: SshPipe
metadata:
  name: sftp-4
spec:
  users:
    - sftp-4
  target:
    name: sftp-4.sftp-4.svc.cluster.local
```

But it looks like I get this errors when trying to connect:

```
connection from xxx.xxx.xxx.xxx:29578 establishing failed reason: dial tcp: lookup sftp-4.sftp-4.svc.cluster.local.sshpiper on 10.245.0.10:53: no such host

```

Has anyone an idea what is going on here and how to solve it?
